name: Repo Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip semgrep
          semgrep scan --config "https://semgrep.dev/p/ci" --exclude node_modules --sarif --output semgrep.sarif ./app
        shell: bash

      - if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/analyze@v3

      - if: matrix.os == 'windows-latest'
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path ./scripts -Recurse -Severity Warning
        shell: pwsh

      - if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip truffleHog
          trufflehog filesystem --json "$GITHUB_WORKSPACE"
        shell: pwsh
